### PR TITLE
Some refactors

### PR DESCRIPTION
**Pull request by rodrigopedra**
Hi @robinmvd 

Based on your last Laracasts thread I refactored your app to add the favorites feature.

The first commits are small and focused on smaller changed. But then in the last one I changed most of the views and did some other controllers customizations.

I tried adding comments to explain most of the changes. Let me know if you have any additional questions. I'll be happy to answer those.

Hope this helps.

### CODE REVIEW

**Comment by robinmvd** [comment]
@rodrigopedra Thank you so much for your help! The comments are really helpful I will definitely learn a lot :)

**Comment by rodrigopedra** [comment]
You're welcome @robinmvd ! Let me know if you have additional questions or want any help on how to merge these changes.

**Comment by rodrigopedra** [comment]
One additional note I missed adding comments about:

As you are using Bootstrap CSS framework, I noticed some buttons were missing the `btn` class. I added this class to the buttons I found missing it.

Bootstrap uses some classes to compose the look and feel, for example:

~~~html
<button type="button" class="btn btn-sm btn-warning">Click Me</button>
~~~

In this buttons there are 3 classes applied:

- `btn` is the that resets the browser's native styles for the buttons and apply any "structural styles" such as paddings, borders and font-size
- `btn-sm` is an optional one that changed some of the styles applied by `btn` regarding the button's sizing
- `btn-warning` adds coloring to the button's font face and background.

So it is important to always add the `btn` and one of the coloring ones to properly style a button using Bootstrap.

Also I noticed you had some anchor tags (`<a href="...">...</a>`) wrapping or inside a button.

According to the HTML spec it is not recommended to place an interactive element (`<button>`, `<a>`, `<input>`, `<select>`, `<textarea>`, ...) within another interactive element. It can lead to unexpected results and decreased accessibility.

If you want a link to another page styled as a button you can apply those buttons classes mentioned above to the anchor tag itself, and it will be styled as a button properly, for example:

~~~html
<a href="btn btn-primary" href="/another-page">Hey! I look I like a button!</a>
~~~

Hope this helps.

**Comment by robinmvd** [comment]
Hey @rodrigopedra thank you for helping me so much. I applied your changes but i get this error.

(didn't merge your changes yet but applied it in a copy of this project so I could read al the code and your comments step by step.)

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'redex.favorites' doesn't exist (SQL: select `id` from `favorites` where `favorites`.`user_id` = 1 and `favorites`.`user_id` is not null)
```
on line 67 of BookController.php

```
        $favorites = $request->user()->favorites()->pluck('id');
```

Any idea how I can solve this?

**Comment by rodrigopedra** [comment]
Hi @robinmvd 

You'll need to run the migrations as the migration for the favorites table is a new one:

~~~bash
php artisan migrate
~~~

Actually as there are some changes on other migrations you could ask Laravel to rerun all migrations, but you'll loose any previous data. Shouldn't be a problem if you are still in early development:

~~~bash
php artisan migrate:fresh
~~~

Let me know if that worked out for you.

**Comment by rodrigopedra** [comment]
Also, you said you applied each change one-by-one, which is great for learning. 

I would appreciate any feedback if the comments, or the changes were clear enough to help you on understanding what was been done.

Thanks

**Comment by robinmvd** [comment]
@rodrigopedra Thank you for your help.
I tried what you suggested but it still gives the same error. Everything migrated fine with no errors when i did ```php artisan migrate:fresh ```.

**Comment by rodrigopedra** [comment]
1. Did you create the ` database/migrations/2020_11_30_025226_create_favorites_table.php` file? It is listed on the "Files changed" tab above:
  https://github.com/robinmvd/redex/pull/2/files#diff-28cef7fab62f346303f524399f915b1b5ea9d53d11b70bcb098b4f69b714bf1f
2. Can you rerun `php artisan migrate:fresh` and post the results?

**Comment by rodrigopedra** [comment]
Hi @robinmvd 

1. Did you create the ` database/migrations/2020_11_30_025226_create_favorites_table.php` file? It is listed on the "Files changed" tab above:
  https://github.com/robinmvd/redex/pull/2/files#diff-28cef7fab62f346303f524399f915b1b5ea9d53d11b70bcb098b4f69b714bf1f
2. Can you rerun `php artisan migrate:fresh` and post the results?

**Comment by robinmvd** [comment]
@rodrigopedra when i run ```php artisan migrate:fresh``` everything seems okay.

i get:
```
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (87.13ms)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (62.81ms)
Migrating: 2019_08_19_000000_create_failed_jobs_table
Migrated:  2019_08_19_000000_create_failed_jobs_table (29.30ms)
Migrating: 2020_09_24_144212_create_categories_table
Migrated:  2020_09_24_144212_create_categories_table (15.44ms)
Migrating: 2020_09_27_122155_create_books_table
Migrated:  2020_09_27_122155_create_books_table (73.11ms)
Migrating: 2020_09_27_122943_create_comments_table
Migrated:  2020_09_27_122943_create_comments_table (96.35ms)
Migrating: 2020_11_30_025226_create_favorites_table
Migrated:  2020_11_30_025226_create_favorites_table (75.95ms)
```
But then when i register a user the application shows this error:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list' (SQL: select `id` from `favorites` where `favorites`.`user_id` = 1 and `favorites`.`user_id` is not null)
```

**Comment by rodrigopedra** [comment]
Hi @robinmvd 

I tried running migrate:fresh locally and it worked.

Can you clone my fork locally and test it?

~~~
git clone git@github.com:rodrigopedra/redex.git test-redex
cd test-redex
composer install
npm ci
npm run prod
php artisan migrate
php artisan serve
~~~

If it works you should try to compare the changes with your code base, maybe you missed some change.

You can also try merging this PR and running `git pull --force` on your machine. Note that using `--force` might undo any other changes you already made to conflicting files.

If you need further assistance we could make a short skype call (or zoom, hangouts, etc.)

**Comment by rodrigopedra** [comment]
Also, if you can please post the whole stack trace of the error message.

**Comment by robinmvd** [comment]
@rodrigopedra https://flareapp.io/share/lm23qN0P#F57
I'm going to try to clone your fork and test that :)

**Comment by rodrigopedra** [comment]
@robinmvd How is the `favorites` relation defined in the `User` model?

From my changes it should be a `belongsToMany` relation with the `Book` model:

~~~php
    /**
     * There is already a relation named books
     */
    public function favorites()
    {
        // 'favorites' here is the pivot table name
        return $this->belongsToMany(Book::class, 'favorites')
            // tell Laravel to use the custom pivot model
            // instead of a shallow model
            ->using(Favorite::class)

            // tell Laravel the pivot model has timestamps
            ->withTimestamps()

            // tell Laravel to name this relation
            // as `favorites` instead of `pivot`
            // when retrieving models
            ->as('favorites');
    }
~~~

https://github.com/robinmvd/redex/pull/2/files#diff-37a2d7d879a7de3f7d73b2975cd22be9f41ec10c334a0dda9ad1e869332e4ecb

**Comment by robinmvd** [comment]
@rodrigopedra Yes that was it! Thank you!

**Comment by rodrigopedra** [comment]
Great you got it working @robinmvd !

As it seems you are using PHPStorm (from the `.idea` folder committed in the repo) one thing you can try is to fork my repo into another folder and using the "Compare with..." tool to do a side-by-side comparison between my fork and your repo.

You can right-click the top folder on the project and the tool will be available from the context menu. Then you select the folder and a new window will popup that will let you compare both versions side-by-side. Then you can edit in place or click the middle column for accepting any changes. Pay attention to the icons on this middle column as they will point to each direction it will be copying over.

One tip is to delete both `./node_modules` and `./vendor` folders from both folders to reduce compared files.

I'll send another PR on a future date regarding your usage of the `.gitignore` file. Right now as you are using it for learning purposes there is not a problem, but I can senf a PR with an optimal usage suggestion with a more in-depth explanation on the changes, if you want to.

Have a nice day =)

**Comment by rodrigopedra** [comment]
Closing per recent changes

**Pull request closed without merging**
